FROM bellsoft/liberica-runtime-container:jdk-17-stream-musl as builder
WORKDIR /home/myapp
COPY demo /home/myapp/demo
# fix
WORKDIR /home/myapp/demo/docker-image-demo
RUN ./mvnw package
FROM bellsoft/alpaquita-linux-base:stream-musl
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
VOLUME /tmp
WORKDIR /home/myapp
COPY --from=builder /home/myapp/demo/target .
EXPOSE 8080
CMD ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]
